services:
  - type: web
    name: findit
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd school_map_project/schoolmap && gunicorn schoolmap.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0